name: Bug Report
description: Report an issue or bug with wordlist-tool
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Detailed description of the behavior.
    validations:
      required: true
